CFLAGS=-Wall -g

all: break_interrompe \
		comparaab continue_desvio \
		entre10e20 \
		do_while \
		entre10e20 \
		for_cont for_cont_decremento \
		if5 \
		laco_infinito \
		menorq20 mostrado10vezes menor_deles menor_deles_resposta\
		nota7 notas_alunos \
		semana \
		whilenota

clean:
	rm -rf break_interrompe \
		comparaab continue_desvio \
		entre10e20 \
		do_while \
		entre10e20 \
		for_cont for_cont_decremento \
		if5 \
		laco_infinito \
		menorq20 mostrado10vezes menor_deles menor_deles_resposta\
		nota7 notas_alunos \
		semana \
		whilenota

