CFLAGS=-Wall -g -c

#
# Este Makefile precisa ser revisto,
# ele não está gerando os executáveis no linux.
# 

all: equacao \
		equacao2 \
		exercicio4 \
		fatorial2 \
		fatorial \
		media_globais \
		media_param2 \
		media_param \
		media_proc \
		media_sem_proc \
		retorno_func \
		retorno_proc \
		situacao \
		situacao_prot \
		sombra \
		troca \
		troca_glob \
		troca_main \
		troca_ref


clean:
	rm -rf \
		equacao2 \
		equacao \
		exercicio4 \
		fatorial2 \
		fatorial \
		media_globais \
		media_param2 \
		media_param \
		media_proc \
		media_sem_proc \
		retorno_func \
		retorno_proc \
		situacao \
		situacao_prot \
		sombra \
		troca \
		troca_glob \
		troca_main \
		troca_ref
