Este livro é destinado a alunos de cursos como Ciência da Computação,
Sistemas de Informação, Engenharia da Computação e, sobretudo,
Licenciatura em Computação. Ele tem o objetivo de apresentar os
principais conceitos da programação de computadores, de modo que sua
utilização é mais adequado a disciplinas introdutórias como a de
Introdução à Programação. De forma alguma o presente livro tem a
pretensão de cobrir todos os assuntos relacionados à área de
programação. Sua principal finalidade é a de servir como guia para os
alunos que estão dando os primeiros passos nessa área que é tão
importante para a ciência da computação. 

A disciplina de Introdução à Programação é a primeira de uma sequência
de disciplinas que têm o objetivo de tornar os alunos capazes dominar
os fundamentos e as técnicas relacionadas à programação de
computadores. Durante o curso de Licenciatura em Computação,
especificamente, os alunos terão a chance de conhecer em detalhes
algumas das linguagens de programação mais utilizadas atualmente e
estarão habilitados a ministrar cursos de programação para diversos
públicos.

Mais importante do que conhecer as peculiaridades das linguagens de
programação é aprender como funciona a lógica aplicada na elaboração
de soluções desenvolvidas a partir de algoritmos computacionais. Sendo
assim, o principal objetivo deste livro é ensiná-los a resolver
problemas com base nos comandos e mecanismos presentes nas linguagens
de programação, desenvolvendo assim o que chamamos de lógica de
programação. No decorrer do livro, o leitor aprenderá gradativamente a
dar instruções ao computador através de programas que ele próprio será
capaz de criar. Para isso, conhecerá a linguagem de programação C, uma
das mais utilizadas e mais importantes linguagens na área de Ciência
da Computação.

No Capítulo 1 será abordado o conceito de algoritmo, e suas principais
formas de representação serão apresentadas. No Capítulo 2, descrevemos
todo o processo de tradução de um programa escrito em linguagem de
alto nível para um programa equivalente em código de máquina, isto é,
a linguagem que os computadores conhecem. Além disso, será apresentado
ao leitor a estrutura de um programa na linguagem C, o que o
habilitará o leitor a desenvolver seu primeiro programa. O Capítulo 3
consiste no conteúdo do livro que mais desenvolve a lógica de
programação. É nele que se encontram as principais instruções de uma
linguagem de programação: as estruturas de controle. No Capítulo 4
será apresentado o conceito de arranjos e, por fim, no Capítulo 5,
explicaremos como programas complexos podem ser divididos em programas
menores, mais fáceis de serem solucionados, através da utilização das
funções.

Recomendamos ao aluno, iniciante na programação de computadores, que
não se limite à leitura e ao conteúdo deste livro. Pesquise na
internet outros materiais, leia outros livros e faça todos os
exercícios propostos. Programação, assim como matemática, requer muito
exercício, muita prática. Como mencionado anteriormente, a programação
de computadores é uma das subáreas mais importantes da carreira que
você escolheu seguir. Boa parte das disciplinas do seu curso depende
do conhecimento adquirido em Introdução à Programação. Portanto,
dedique o máximo que puder ao aprendizado de uma área que vai
permiti-lo transformar sonhos em realidade.
 

=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em Computação, na
modalidade a distância footnote::[Embora ele tenha sido feito para atender aos alunos
da Universidade Federal da Paraíba, o seu uso não se restringe a esta 
universidade, podendo ser adotado por outras universidades do sistema UAB.].
Ele foi concebido para ser utilizado numa disciplina de 'Introdução à Programação',
no primeiro semestre do curso.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

// Sempre manter uma linha em branco no final
