CC = gcc

all: break_interrompe.exe \
		comparaab.exe continue_desvio.exe \
		entre10e20.exe \
		do_while.exe \
		entre10e20.exe \
		for_cont.exe for_cont_decremento.exe \
		if5.exe \
		laco_infinito.exe \
		menorq20.exe mostrado10vezes.exe menor_deles.exe menor_deles_resposta.exe\
		nota7.exe notas_alunos.exe \
		semana.exe \
		whilenota.exe

break_interrompe.exe: break_interrompe.c
	${CC} -o break_interrompe.exe break_interrompe.c

comparaab.exe: comparaab.c
	${CC} -o comparaab.exe comparaab.c

continue_desvio.exe: continue_desvio.c
	${CC} -o continue_desvio.exe continue_desvio.c

do_while.exe: do_while.c
	${CC} -o do_while.exe do_while.c

entre10e20.exe: entre10e20.c
	${CC} -o entre10e20.exe entre10e20.c

for_cont.exe: for_cont.c
	${CC} -o for_cont.exe for_cont.c

for_cont_decremento.exe: for_cont_decremento.c
	${CC} -o for_cont_decremento.exe for_cont_decremento.c

if5.exe: if5.c
	${CC} -o if5.exe if5.c

laco_infinito.exe: laco_infinito.c
	${CC} -o laco_infinito.exe laco_infinito.c

menor_deles.exe:
	${CC} -o menor_deles.exe menor_deles.c

menor_deles_resposta.exe: menor_deles_resposta.c
	${CC} -o menor_deles_resposta.exe menor_deles_resposta.c

menorq20.exe: menorq20.c
	${CC} -o menorq20.exe menorq20.c

mostrado10vezes.exe: mostrado10vezes.c
	${CC} -o mostrado10vezes.exe mostrado10vezes.c

nota7.exe: nota7.c
	${CC} -o nota7.exe nota7.c

notas_alunos.exe: notas_alunos.c
	${CC} -o notas_alunos.exe notas_alunos.c

semana.exe: semana.c
	${CC} -o semana.exe semana.c

whilenota.exe: whilenota.c
	${CC} -o whilenota.exe whilenota.c

clean:
	rm -rf *.exe *.orig

